# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Big Mingo
tagline:          'A blog'
description:      'A blogging website for an aspiring student in Cybsersecurity. A project by <a href="https://www.linkedin.com/in/austin-ingram-a185b1256" target="_blank">Austin</a>.'
url:              http://bigmingo.github.io/hyde
baseurl:          '/hyde/'

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
